name: Issues Ejemplo

on:
  issues:
    types: [opened]

jobs:
  procesa-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra el título del issue
        run: echo " El título de este Issue es ${{ github.event.issue.title }} "
