name: Variables y Secretos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimiendo variables y secretos
        run: |
          echo "La variable es ${{ vars.MI_VARIABLE }}
          echo "El secrto es ${{ secrets.CONNECTION_STRING }}

      # Para leer el codigo fuente
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Correr codigo de JS
        run: node main.js
        # Asignamos la variable de entorno para que el JS la use
        env:
          # Usamos la varible del JS
          VARIABLE_CENTRALIZADA: ${{ vars.MI_VARIABLE }}
