name: Variables y Secretos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimiendo variables y secretos
        run: |
          echo "La variable es ${{ vars.MI_VARIABLE }}
          echo "El secrto es ${{ secrets.CONNECTION_STRING }}
          
